-- ═══════════════════════════════════════════════════════════════
-- 0042 · Havells prune (generated by scripts/gen-havells-import.mjs)
--
-- Elume Havells products NOT found anywhere on havells.com (2026-07-14T12:21:39.371Z,
-- matched by manufacturer SKU against every product and colour variant,
-- including out-of-stock listings). Per user decision: rows referenced by an
-- order are ARCHIVED (is_active = false, hidden by RLS); the rest are deleted.
-- competitor_map / competitor_prices / reviews cascade on delete.
-- ═══════════════════════════════════════════════════════════════

-- 16 product(s): hav-amb-1200, hav-iso-40, hav-rccb-40, havpanel, wire-havells-frlsh-0p5-black, wire-havells-frlsh-0p5-blue, wire-havells-frlsh-0p5-green, wire-havells-frlsh-0p5-grey, wire-havells-frlsh-0p5-red, wire-havells-frlsh-0p5-yellow, wire-havells-frlsh-0p75-black, wire-havells-frlsh-0p75-blue, ...

update public.products p set is_active = false
where p.id in (
  'hav-amb-1200',
  'hav-iso-40',
  'hav-rccb-40',
  'havpanel',
  'wire-havells-frlsh-0p5-black',
  'wire-havells-frlsh-0p5-blue',
  'wire-havells-frlsh-0p5-green',
  'wire-havells-frlsh-0p5-grey',
  'wire-havells-frlsh-0p5-red',
  'wire-havells-frlsh-0p5-yellow',
  'wire-havells-frlsh-0p75-black',
  'wire-havells-frlsh-0p75-blue',
  'wire-havells-frlsh-0p75-green',
  'wire-havells-frlsh-0p75-grey',
  'wire-havells-frlsh-0p75-red',
  'wire-havells-frlsh-0p75-yellow'
)
and exists (select 1 from public.orders o where o.items @> jsonb_build_array(jsonb_build_object('id', p.id)));

delete from public.products p
where p.id in (
  'hav-amb-1200',
  'hav-iso-40',
  'hav-rccb-40',
  'havpanel',
  'wire-havells-frlsh-0p5-black',
  'wire-havells-frlsh-0p5-blue',
  'wire-havells-frlsh-0p5-green',
  'wire-havells-frlsh-0p5-grey',
  'wire-havells-frlsh-0p5-red',
  'wire-havells-frlsh-0p5-yellow',
  'wire-havells-frlsh-0p75-black',
  'wire-havells-frlsh-0p75-blue',
  'wire-havells-frlsh-0p75-green',
  'wire-havells-frlsh-0p75-grey',
  'wire-havells-frlsh-0p75-red',
  'wire-havells-frlsh-0p75-yellow'
)
and not exists (select 1 from public.orders o where o.items @> jsonb_build_array(jsonb_build_object('id', p.id)));
