-- 0097: Extension Boards category - 7 brands, official-source data.
-- Idempotent: inserts use on conflict do nothing; updates are absolute.
--
-- Sources (Aug 2026):
--   Havells    - already imported Jul 2026 from havells.com (9 boards moved
--                here from Electrical Accessories, proper attrs added)
--   Anchor     - lsin.panasonic.com official catalogue + Moglix/BigBasket prices
--   GM Modular - gmmodular.com official catalogue + Flipkart/dealer prices
--   Goldmedal  - Elecload dealer listings (official cat. numbers, MRP+street)
--   Orient     - orientelectric.com official store (MRP, price, photos)
--   Wipro      - ShopClues/Flipkart listings
--   Syska      - IndiaMART dealer / Flipkart listings
-- Pricing: elume_price = verified street price - 2% (MRP = street where no
-- separate MRP was published - shown as 0% off, never inflated).
-- Photos: official CDN URLs where available; missing photos ship imageless
-- (storefront fallbacks cover it) for the next photo pass.
-- HSN 8536 (plugs/sockets/boards), 18% GST via category default.
--
-- After running: hit "Rebuild mappings now" in /admin/compare so the new
-- category's like-to-like groups build.

-- Havells: move the 9 existing boards into the new category
update public.products set category = 'Extension Boards', attrs = '{"Sockets": "4", "Rating": "6 A", "Cord": "1.5 m"}'::jsonb where id = 'hav-ahlklcw064';
update public.products set category = 'Extension Boards', attrs = '{"Sockets": "3", "Rating": "6 A", "Cord": "5 m"}'::jsonb where id = 'hav-ahexxxu065';
update public.products set category = 'Extension Boards', attrs = '{"Sockets": "3", "Rating": "6 A", "Cord": "5 m"}'::jsonb where id = 'hav-ahnxxxu065';
update public.products set category = 'Extension Boards', attrs = '{"Sockets": "3", "Rating": "6 A", "Cord": "1.5 m", "USB": "3"}'::jsonb where id = 'hav-ahnkxxg063';
update public.products set category = 'Extension Boards', attrs = '{"Sockets": "4", "Rating": "6 A", "Cord": "2 m"}'::jsonb where id = 'hav-ahnkxxr000';
update public.products set category = 'Extension Boards', attrs = '{"Sockets": "4", "Rating": "6 A", "Cord": "4 m"}'::jsonb where id = 'hav-ahnkxxr004';
update public.products set category = 'Extension Boards', attrs = '{"Sockets": "4", "Rating": "6 A", "Cord": "2 m"}'::jsonb where id = 'hav-ahnkxxw101';
update public.products set category = 'Extension Boards', attrs = '{"Sockets": "5", "Rating": "6 A", "Cord": "1.5 m"}'::jsonb where id = 'hav-ahnxoxf06x';
update public.products set category = 'Extension Boards', attrs = '{"Sockets": "4", "Rating": "6 A"}'::jsonb where id = 'hav-ahekxxb061';

-- New products: Anchor, GM Modular, Goldmedal, Orient, Wipro, Syska
insert into public.products
  (id, sku, name, brand, category, spec, mrp, elume_price, unit, image_url, hsn, is_active, in_stock, attrs, sort_order, parent_id)
values
  ('anc-22047', '22047', 'Anchor by Panasonic Spike Guard 4 Universal Socket · Single Switch · 1.5 m', 'Anchor', 'Extension Boards', 'Extension board spike guard · 4 universal sockets · single master switch · 6 A 240 V · 1.5 m cord · polycarbonate body · surge & spike protection · Anchor by Panasonic cat. no. 22047', 819, 444, 'pc', 'https://d32zxht0g2dn3w.cloudfront.net/s3fs-public/product_image/switches_sockets/22047_F.png', '8536', true, true, '{"Sockets": "4", "Rating": "6 A", "Cord": "1.5 m"}'::jsonb, 9000, null),
  ('anc-22568', '22568', 'Anchor by Panasonic Spike Guard 4 Universal Socket · Individual Switches', 'Anchor', 'Extension Boards', 'Extension board spike guard · 4 universal shuttered sockets · individual switch per socket · 6 A 240 V · surge & spike protection · child-safety shutters · Anchor by Panasonic cat. no. 22568', 962, 547, 'pc', 'https://d32zxht0g2dn3w.cloudfront.net/s3fs-public/product_image/switches_sockets/22568_F.png', '8536', true, true, '{"Sockets": "4", "Rating": "6 A"}'::jsonb, 9001, null),
  ('anc-22648', '22648', 'Anchor by Panasonic Spike Guard 4 Universal Socket · 10 A · 1.5 m', 'Anchor', 'Extension Boards', 'Heavy-duty extension board spike guard · 4 universal sockets · 10 A rating · 1.5 m cord · surge & spike protection · Anchor by Panasonic cat. no. 22648', 1008, 988, 'pc', null, '8536', true, true, '{"Sockets": "4", "Rating": "10 A", "Cord": "1.5 m"}'::jsonb, 9002, null),
  ('anc-22053', '22053', 'Anchor by Panasonic Spike Guard 4 Socket · 4 Switches · 10 A · 1.5 m', 'Anchor', 'Extension Boards', 'Heavy-duty extension board spike guard · 4 sockets with individual switches · 10 A rating · 1.5 m cord · surge & spike protection · Anchor by Panasonic cat. no. 22053', 1988, 1948, 'pc', null, '8536', true, true, '{"Sockets": "4", "Rating": "10 A", "Cord": "1.5 m"}'::jsonb, 9003, null),
  ('gm-3202', 'GM 3202', 'GM Modular Spike Shield 4+1 Spike Guard', 'GM Modular', 'Extension Boards', 'Extension board spike guard · 4 sockets + master switch · 6 A · surge protector · power strip · GM 3202', 849, 832, 'pc', 'https://gmmodular.com/public/live/products/product_thumb/gm_3202_white-white-250X250.png', '8536', true, true, '{"Sockets": "4", "Rating": "6 A"}'::jsonb, 9004, null),
  ('gm-3205', 'GM 3205', 'GM Modular Quadro 8+1 Spike Guard · 2 USB', 'GM Modular', 'Extension Boards', 'Extension board spike guard · 8 sockets + master switch · 2 USB charging ports · 6 A · surge protector · GM 3205', 1574, 1543, 'pc', 'https://gmmodular.com/public/live/products/product_thumb/gm_3205_white-white-250X250.png', '8536', true, true, '{"Sockets": "8", "Rating": "6 A", "USB": "2"}'::jsonb, 9005, null),
  ('gm-3254', 'GM 3254', 'GM Modular Lemoid 4+1 Spike Guard · 3 International Sockets · USB', 'GM Modular', 'Extension Boards', 'Extension board spike guard · 4 sockets incl. 3 international sockets + master switch · USB charging port · 6 A · surge protector · GM 3254', 1240, 1215, 'pc', 'https://gmmodular.com/public/live/products/product_thumb/gm_3254_white-white-250X250.png', '8536', true, true, '{"Sockets": "4", "Rating": "6 A", "USB": "1"}'::jsonb, 9006, null),
  ('gm-3260', 'GM 3260', 'GM Modular Lemoid 4+1 Spike Guard · 3 USB 2.1 A', 'GM Modular', 'Extension Boards', 'Extension board spike guard · 4 sockets + master switch · 3 USB ports 2.1 A · 6 A · surge protector · GM 3260', 1220, 1196, 'pc', 'https://gmmodular.com/public/live/products/product_thumb/gm_3260_white-white-250X250.png', '8536', true, true, '{"Sockets": "4", "Rating": "6 A", "USB": "3"}'::jsonb, 9007, null),
  ('gold-205104', '205104', 'Goldmedal 360° Spike Guard · 6 Socket', 'Goldmedal', 'Extension Boards', 'Extension board spike guard · 6 sockets · 360° rotating design · MOV surge protection · wall-mountable · Curve Plus series · cat. no. 205104', 828, 529, 'pc', 'https://elecload.com/wp-content/uploads/2022/06/236089_3_kz96pi.png', '8536', true, true, '{"Sockets": "6", "Rating": "6 A"}'::jsonb, 9008, null),
  ('gold-205100', '205100', 'Goldmedal 360° Power Strip', 'Goldmedal', 'Extension Boards', 'Extension board power strip · 360° rotating sockets · MOV surge protection · spike guard · cat. no. 205100', 1399, 892, 'pc', null, '8536', true, true, '{"Rating": "6 A"}'::jsonb, 9009, null),
  ('gold-205106', '205106', 'Goldmedal 360° Spike Guard · USB', 'Goldmedal', 'Extension Boards', 'Extension board spike guard · 360° rotating sockets · USB charging ports · MOV surge protection · cat. no. 205106', 1300, 828, 'pc', null, '8536', true, true, '{"Rating": "6 A", "USB": "1"}'::jsonb, 9010, null),
  ('gold-205102', '205102', 'Goldmedal i-Design 4×1 Power Strip', 'Goldmedal', 'Extension Boards', 'Extension board power strip · 4 sockets + master switch · MOV surge protection · spike guard · compact desk design · cat. no. 205102', 709, 451, 'pc', null, '8536', true, true, '{"Sockets": "4", "Rating": "6 A"}'::jsonb, 9011, null),
  ('gold-205103', '205103', 'Goldmedal i-Design 4×4 Power Strip', 'Goldmedal', 'Extension Boards', 'Extension board power strip · 4 universal sockets with individual switches · MOV surge protection · spike guard · cat. no. 205103', 1018, 647, 'pc', null, '8536', true, true, '{"Sockets": "4", "Rating": "6 A"}'::jsonb, 9012, null),
  ('gold-205107', '205107', 'Goldmedal i-Design 4×4 Power Strip · USB', 'Goldmedal', 'Extension Boards', 'Extension board power strip · 4 universal sockets with individual switches · USB charging · MOV surge protection · spike guard · cat. no. 205107', 1399, 892, 'pc', null, '8536', true, true, '{"Sockets": "4", "Rating": "6 A", "USB": "1"}'::jsonb, 9013, null),
  ('gold-205101', '205101', 'Goldmedal i-Strip LED Spike Guard', 'Goldmedal', 'Extension Boards', 'Extension board spike guard · LED power indicator · MOV surge protection · power strip · cat. no. 205101', 1162, 740, 'pc', null, '8536', true, true, '{"Rating": "6 A"}'::jsonb, 9014, null),
  ('ori-16a-power-2m', 'ORI-16A-2M', 'Orient Electric 16 A Power Extension Board · 2 m', 'Orient', 'Extension Boards', 'Heavy-duty power extension board · 16 A 240 V · up to 2500 W (geysers, heaters, power tools) · universal sockets · MCB overload & short-circuit protection · brass contacts · 2 m cord', 1270, 871, 'pc', 'https://orientelectric.com/cdn/shop/files/16a-power-extension-board-orient-electric-1.png', '8536', true, true, '{"Rating": "16 A", "Cord": "2 m"}'::jsonb, 9015, null),
  ('ori-4x4-2m', 'ORI-4X4-2M', 'Orient Electric 4×4 Socket Extension Board · 2 m · White', 'Orient', 'Extension Boards', 'Extension board · 4 sockets with individual switches · 6 A · 2 m cord · spike guard · white', 774, 531, 'pc', 'https://orientelectric.com/cdn/shop/files/4x4-socket-extension-board-with-2-metre-wire-white-orient-electric-1.png', '8536', true, true, '{"Sockets": "4", "Rating": "6 A", "Cord": "2 m"}'::jsonb, 9016, null),
  ('ori-4s-2m', 'ORI-4S-2M', 'Orient Electric 4 Socket Extension Board · 2 m · White', 'Orient', 'Extension Boards', 'Extension board · 4 sockets · single switch · 6 A · 2 m cord · spike guard · white', 622, 426, 'pc', 'https://orientelectric.com/cdn/shop/files/4-socket-extension-board-with-2-metre-wire-white-orient-electric-1.png', '8536', true, true, '{"Sockets": "4", "Rating": "6 A", "Cord": "2 m", "Colour": "White"}'::jsonb, 9017, null),
  ('ori-4s-2m-blk', 'ORI-4S-2M-BLK', 'Orient Electric 4 Socket Extension Board · 2 m · Black', 'Orient', 'Extension Boards', 'Extension board · 4 sockets · single switch · 6 A · 2 m cord · spike guard · black', 818, 561, 'pc', 'https://orientelectric.com/cdn/shop/files/4-socket-extension-board-with-2-metre-wire-black-orient-electric-1.png', '8536', true, true, '{"Sockets": "4", "Rating": "6 A", "Cord": "2 m", "Colour": "Black"}'::jsonb, 9018, 'ori-4s-2m'),
  ('ori-4s-5m', 'ORI-4S-5M', 'Orient Electric 4 Socket Extension Board · 5 m', 'Orient', 'Extension Boards', 'Extension board · 4 sockets · single switch · 6 A · 5 m cord · spike guard', 860, 590, 'pc', 'https://orientelectric.com/cdn/shop/files/4-socket-extension-board-with-5-metre-wire-orient-electric-1.png', '8536', true, true, '{"Sockets": "4", "Rating": "6 A", "Cord": "5 m"}'::jsonb, 9019, null),
  ('wip-guardian-4w', 'WIP-GUARD-4W', 'Wipro Guardian 4 Way Extension Socket with Spike Guard', 'Wipro', 'Extension Boards', 'Extension board spike guard · 4 sockets · surge protection · extension socket', 690, 489, 'pc', null, '8536', true, true, '{"Sockets": "4", "Rating": "6 A"}'::jsonb, 9020, null),
  ('wip-essential-4x4', 'WIP-ESS-4X4', 'Wipro Essential 4 Plus 4 Socket Extension Board', 'Wipro', 'Extension Boards', 'Extension board · 4 universal sockets with 4 individual switches · spike guard · surge protection', 1149, 1126, 'pc', null, '8536', true, true, '{"Sockets": "4", "Rating": "6 A"}'::jsonb, 9021, null),
  ('sys-0401', 'SSK-0401', 'Syska 0401 4 Socket Power Strip Spike Buster', 'Syska', 'Extension Boards', 'Extension board power strip · 4 sockets · spike buster surge protection · model 0401', 398, 390, 'pc', null, '8536', true, true, '{"Sockets": "4", "Rating": "6 A"}'::jsonb, 9022, null),
  ('sys-0402', 'SSK-0402', 'Syska 0402 4 Socket Power Strip · Individual Switches', 'Syska', 'Extension Boards', 'Extension board power strip · 4 sockets with individual switches · spike buster surge protection · model 0402', 459, 449, 'pc', null, '8536', true, true, '{"Sockets": "4", "Rating": "6 A"}'::jsonb, 9023, null),
  ('sys-3way-usb', 'SSK-3W-USB', 'Syska 3 Way Power Strip · 2 USB', 'Syska', 'Extension Boards', 'Extension board power strip · 3 universal sockets · 2 USB charging ports · surge protection · spike guard', 799, 570, 'pc', null, '8536', true, true, '{"Sockets": "3", "Rating": "6 A", "USB": "2"}'::jsonb, 9024, null),
  ('sys-4way', 'SSK-4W', 'Syska 4 Way Power Strip', 'Syska', 'Extension Boards', 'Extension board power strip · 4 sockets · surge protection · spike guard', 499, 312, 'pc', null, '8536', true, true, '{"Sockets": "4", "Rating": "6 A"}'::jsonb, 9025, null)
on conflict (id) do nothing;
